newserver/config/routes.rb
Newserver::Application.routes.draw do
  resources :goals do
    member do 
      get :adopt
      get :unadopt
    end
    
    resources :notes
    resources :users
    resources :sources
  end
  
  resources :notes do
    member do 
       get :full_text
       put :set_goals
    end
  end

  resources :users do
    collection do 
      get :logout
      post :login
    end
  end
  
  resources :sources
  get 'me', :to => 'users#me', :as => 'me'
  get 'api_key.:format', :to => 'users#api_key', :as => 'api_key'
  get 'verify_api_key.:format', :to => 'users#verify_api_key', :as => 'verify_api_key'
  get 'export', :to => 'goals#export', :as => 'export'
  get 'goals/:id/export', :to => 'goals#download_csv'
  get 'add_comment', :to => 'notes#add_comment'
  get 'add_sub_comment', :to => 'nodes#add_sub_comment'
  get 'promote', :to => 'nodes#promote'
  get 'goals/download_csv', :to => 'goals#download_csv', :as => 'download_csv'
  get 'search', :to => 'search#search', :as => 'search'
  get 'inbox', :to => 'notes#inbox', :as => 'inbox'
  get 'inbox_sources', :to => 'sources#inbox', :as => 'inbox_sources'
  get 'all_goals', :to => 'goals#all_goals', :as => 'all_goals'
  get 'all_sources', :to => 'sources#all_sources', :as => 'all_sources'
  get 'my_sources', :to => 'sources#my_sources', :as => 'my_sources'
  get 'my_notes', :to => 'notes#my_notes', :as => 'my_notes'
  get 'all_notes', :to => 'notes#all_notes', :as => 'all_notes'
  get 'create_note', :to => 'notes#create', :as => 'create_note'
  get 'js_lib', :to => 'js_lib#js_lib', :as => 'js_lib'
  root :to => 'welcome#welcome'
end

newserver/app/models/goal.rb
class Goal < ActiveRecord::Base
  has_many :users, :through => :usergoals
  has_many :usergoals
  
  has_many :notes, :through => :notegoals
  has_many :notegoals

  validates_uniqueness_of :name
  
  belongs_to :admin, :class_name => "User"

  def to_s
    name.to_s
  end

  def sources
    Source.find_by_sql ["select distinct sources.* from sources, notes, goals, notegoals 
                         where sources.id = notes.source_id 
                         and notegoals.note_id = notes.id 
                         and notegoals.goal_id = ?", id]
  end

  def subscribers
    User.find_by_sql ["select distinct users.* from users, usergoals, goals
                       where users.id = usergoals.user_id
                       and users.id != goals.admin_id
                       and goals.id = ?
                       and usergoals.goal_id = ?", id, id]

  end
end

#name
#statues
#admin

newserver/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_filter :load_goal, :only => [:show, :edit, :update, :destroy, :adopt, :unadopt]
  before_filter :require_login, :only => [:new, :edit, :create, :update, :destroy, :export, :download_csv, :adopt, :unadopt]
  before_filter :require_admin, :only => [:edit, :update, :delete]

  def load_goal
    @goal = Goal.find(params[:id])
  end

  def require_admin
    unless @current_user == @goal.admin
      flash[:error] = "You are not the admin of this goal."
      redirect_to request.referer
    end
  end
  
  # GET /goals
  def index
    respond_to do |format|
      if @current_user
        format.html {
          @goals = Goal.paginate :page => params[:page],
                                 :include => :usergoals,
                                 :per_page => 20,
                                 :conditions => {'usergoals.user_id' => @current_user.id},
                                 :order => "goals.updated_at desc"
          @heading = "All my Goals"
        }
        @goals ||= Goal.find(:all,
                             :include => :usergoals,
                             :conditions => {'usergoals.user_id' => @current_user.id},
                             :order => "goals.updated_at desc").map{|goal| goal.name}

        format.xml  {render :partial => 'goal.xml'}
        format.json {render :json => @goals}
        format.js   {render :json => @goals, :callback => "charting.setGoals"}
      else 
        format.xml  {render :text => '<error>Not logged in.</error>'}
        format.json {render :json => '"Not logged in."', :status => :forbidden}
        format.js   {render :json => '"Not logged in."', :callback => "charting.goalsError"}
      end
    end
  end

  def all_goals
    @goals = Goal.paginate :page => params[:page],
      :per_page => 20,
      :order => "created_at desc"

    render :index
  end

  # GET /goals/1
  def show
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # export goals
  def export
    respond_to do |format|
      if @current_user
        @goals = Goal.all
        @export = true
        format.html  # export.html.erb
      else
        format.html  { redirect_to(request.referer) }
      end
    end
  end

  # csv popup
  def download_csv

    # get the filename
    id = params[:id]

    # generate the file
    gen_export_csv(id)

    # filename
    filename = "Export#{id}.csv"

    # create the path
    path = File.expand_path RAILS_ROOT + "/exports/" + filename

    # get the filesize
    size = File.size(path)

    if File.exists?(path) & File.readable?(path)
      # send the file
      send_file path,
                :type => "text/csv",
                :disposition => "attachment",
                :length => size,
                :filename => filename
    end
  end

  # GET /goals/new
  def new
    @goal = Goal.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /goals/1/edit
  def edit
    @goal = Goal.find(params[:id])
  end

  # POST /goals
  def create
    @goal = Goal.find_by_name(params[:goal][:name])
    if @goal
      @goal.users << @current_user
      respond_to do |format|
        format.html { redirect_to(goal_notes_path(@goal), :notice => 'Existing goal added to your list.') }
      end
    else
      @goal = Goal.new(params[:goal].permit(:name))
      @goal.admin = @current_user
      @goal.status = "active"

      respond_to do |format|
        if @goal.save
          @current_user.goals << @goal
          format.html { redirect_to(goal_notes_path(@goal), :notice => 'Goal was successfully created.') }
        else
          format.html { render :action => "new" }
        end
      end
    end
  end

  def adopt
    @current_user.goals << @goal
    @current_user.save!
    redirect_to goal_notes_path(@goal)
  end

  def unadopt
    @current_user.goals.delete @goal

    respond_to do |format|
      format.html { redirect_to(request.referer, :notice => 'Unsubscribed from goal.') }
    end
    
  end

  # PUT /goals/1
  def update
    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to(@goal, :notice => 'Goal was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /goals/1
  def destroy
    @current_user.goals.delete @goal

    # see if there are any subscribers
    if @goal.subscribers.length == 0

      # if not, just delete the goal
      @goal.delete

      respond_to do |format|
        format.html { redirect_to(request.referer) }
      end

    # otherwise the user will have to choose a new owner
    else
      
      # goal.admin needs to choose another user
      respond_to do |format|
        format.html { redirect_to(request.referer, :notice => 'Unable to delete goal, it has subscribers.') }
      end
      
    end
    
  end

# helper functions
  def gen_export_csv(id)
    FasterCSV.open("exports/Export#{id}.csv", "w") do |csv|

      # create the title row
      csv << ["Note",
              "Source Name",
              "Source URL",
              "Date Added",
              "Creator"]

      # get the goal
      goal = Goal.find(id)

      # for each note in the goal
      for note in goal.notes do

        csv << [note.body,
                note.source.title,
                note.source.location,
                display_date(note.source.created_at),
                note.user.name]

      end #end for
    end # end open

  end # end def

  # formats the date
  def display_date(date)
    date.strftime("%d %b %y")
  end
end  

newserver/app/helpers/goals_helper.rb
module GoalsHelper

  def link_to_button(value, link, cssclass)
    "<form><input type=\"button\" class=\"" + cssclass + "\" value=\"" + value + "\" onclick = \"window.location.href='" + link + "'\"></form>"
  end
 
end # end mod

newserver/app/views/goals/_goal.xml.erb
<goals>
  <% for goal in @goals %>
    <goal><%=h goal%></goal>
  <% end %>
</goals>

newserver/app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= form_for(@goal) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 53 %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5 %>
  </p>
  <!--p>
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </p-->
  <!-- TODO Add drop down to select admin? -->
  <!--p>
    <%= f.label :admin %><br />
    <%= f.text_field :admin %>
  </p-->
  <p>
    <%= f.submit 'Update', :class => 'bluebutton left' %>
  </p>
  <br /><br />
<% end %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

newserver/app/views/goals/export.html.erb
<table>
  <tr>
    <th colspan = "2">Goals</th>
  </tr>

<% @goals.each do |goal| %>
  <tr>
    <td><%=link_to goal.name, goal_notes_path(goal) %></td>
    <td><% form_tag(download_csv_url) do %>
        <%= hidden_field_tag "id", goal.id %>
        <%= submit_tag "Export Goal" , :class => 'bluebutton right' %>
        <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

newserver/app/views/goals/index.html.erb
<table class="no-borders">


<% @goals.each do |goal| %>
  <tr>
    <td><b><%=link_to goal.name, goal_notes_path(goal) %></b></td>
    <td>
        <div id="actions">

    <% if @current_user == goal.admin %>
      <%= link_to 'Edit', edit_goal_path(goal) %> |
      <%= link_to 'Remove', goal, :confirm => 'Are you sure?', :method => :delete %>
    <% else %>
          <% if @user_goals.include? goal %>
            <%= link_to 'UNSUBSCRIBE', unadopt_goal_path(goal), :confirm => 'Are you sure?' %>
          <% else %>
            <%= link_to 'ADOPT', adopt_goal_path(goal) %>
          <% end %>
    <% end %>
        </div>
      </td>
  </tr>
  <tr>
    <td width="500px"><%=goal.description%></td>
    <td></td>
  </tr>
  <tr>

    <td>Owned by:
      <% if @current_user == goal.admin %>
        <%= link_to "You", user_path(@current_user) %>
      <% else %>
        <%= link_to goal.admin.name, user_path(goal.admin) %>
      <% end %>
    </td>




    <td>Subscribers:
      <% if goal.subscribers.blank? %>
      none
      <% else %>
       <% goal.subscribers.each do |sub| %>
       <%= link_to sub.name, user_path(sub) %>&nbsp;
       <% end %>
     <% end %>
    </td>
  </tr>
  <tr>
    <td colspan="2" class="spacer"></td>
  </tr>
  
<% end %>
</table>

<br />

<%= will_paginate @goals %>

newserver/app/views/goals/new.html.erb
<h1>New goal</h1>

<%= form_for(@goal) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

newserver/app/views/goals/show.html.erb
<table>

<tr>
  <th>Name:</th>
  <td><%=h @goal.name %></td>
</tr>

<tr>
  <th>Description:</th>
  <td><%=h @goal.description %></td>
</tr>


<tr>
  <th>Status:</th>
  <td><%=h @goal.status %></td>
</tr>

<tr>
  <th>Admin:</th>
  <td><%=h @goal.admin %></td>
</tr>

</table>