newserver/config/routes.rb
Newserver::Application.routes.draw do
  resources :goals do
    member do 
      get :adopt
      get :unadopt
    end
    
    resources :notes
    resources :users
    resources :sources
  end
  
  resources :notes do
    member do 
       get :full_text
       put :set_goals
    end
  end

  resources :users do
    collection do 
      get :logout
      post :login
    end
  end
  
  resources :sources
  get 'me', :to => 'users#me', :as => 'me'
  get 'api_key.:format', :to => 'users#api_key', :as => 'api_key'
  get 'verify_api_key.:format', :to => 'users#verify_api_key', :as => 'verify_api_key'
  get 'export', :to => 'goals#export', :as => 'export'
  get 'goals/:id/export', :to => 'goals#download_csv'
  get 'add_comment', :to => 'notes#add_comment'
  get 'add_sub_comment', :to => 'nodes#add_sub_comment'
  get 'promote', :to => 'nodes#promote'
  get 'goals/download_csv', :to => 'goals#download_csv', :as => 'download_csv'
  get 'search', :to => 'search#search', :as => 'search'
  get 'inbox', :to => 'notes#inbox', :as => 'inbox'
  get 'inbox_sources', :to => 'sources#inbox', :as => 'inbox_sources'
  get 'all_goals', :to => 'goals#all_goals', :as => 'all_goals'
  get 'all_sources', :to => 'sources#all_sources', :as => 'all_sources'
  get 'my_sources', :to => 'sources#my_sources', :as => 'my_sources'
  get 'my_notes', :to => 'notes#my_notes', :as => 'my_notes'
  get 'all_notes', :to => 'notes#all_notes', :as => 'all_notes'
  get 'create_note', :to => 'notes#create', :as => 'create_note'
  get 'js_lib', :to => 'js_lib#js_lib', :as => 'js_lib'
  root :to => 'welcome#welcome'
end

newserver/app/views/layouts/_login.html.erb
<div id="login">
<% if @current_user %>
  Hello <%=link_to @current_user.name, @current_user%>.<br/><%= link_to "logout", logout_users_path %> | <%= link_to "edit profile", edit_user_path(@current_user) %>
<% else %>
  <%= form_for :login, :url => {:controller => :users, :action => :login} do |f| %>
  <div id="login-right">
  <table class="loginsignup">
   <tr>
    <td>
    <%= f.text_field :username, :size => 15 %>
    <%= f.password_field :password, :size => 15 %>
    </td>
    <td>
    <%= f.submit :login, :class => 'whitebutton left' %>
    </td>
    <td>
    &nbsp;or <%= link_to "sign up", new_user_path%>
    </td>
   </tr>
  </table>
  </div>
  <% end %>
<% end  %>
</div>

newserver/app/views/layouts/_search.erb
<div id="search">
  <%= form_for 'search', :url => search_path do |f| %>
    <%= f.text_field :text, 
                     :size => 30,
                     :id => 'search_field', 
                     :value => 'enter search term(s)',
                     :onFocus => 'if (this.value == "enter search term(s)") {this.value = "";};',
                     :onBlur => 'if (this.value == "") {this.value = "enter search term(s)";};' %>
  <% end %>
</div>

newserver/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newserver</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

newserver/app/views/layouts/global.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Charting: <%= controller_name %></title>
  <%= stylesheet_link_tag 'charting' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id ="page">

  <div id = "header">
    <a href="/"><div id = "logo"></div></a>
    <div id="header-right">
      <%= render :partial => 'layouts/login' %>
      <%= render :partial => 'layouts/search' %>
    </div><!-- end header-right -->
  </div><!-- end header -->

  <div id="main">

  <div id="left">
    <div id="goalmenu">
      <!--h2><%=link_to "Charting", root_path%></h2-->
      <% if @current_user %>

      <ul>

        <% if controller_name == "goals" && action_name == "index" %>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %>
        <%=link_to "My Goals", "/goals", :class => 'lih3'%>
        </li>

      <% for goal in @user_goals %>
        <% if goal == @current_goal %>
          <li class="active-goal">
        <% else %>
          <li>
        <%end%>
        <%=link_to goal.name, goal_notes_path(goal) + "/"%>
        </li>
        <% end %>

        <li>
        <%= form_for Goal.new, :html => {:id => "new_goal_form"} do |f| %>
          <%= f.text_field :name,
                           :size => 34,
                           :id => 'new_goal_field',
                           :value => 'new goal',
                           :onFocus => 'if (this.value == "new goal") {this.value = "";};',
                           :onBlur => 'if (this.value == "") {this.value = "new goal";};' %>
        <% end %>
        </li>

        <% if controller_name == "goals" && action_name == "all_goals" %>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %>
        <%=link_to "All goals", all_goals_path, :class => 'lih3'%>
        </li>

        <hr class="menu"></hr>
  
        <% if controller_name == "notes" && action_name == "my_notes" %>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %>
        <%=link_to "My Notes", my_notes_path, :class => 'lih3' %>
          </li>

        <% if controller_name == "notes" && action_name == "inbox" %>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %> &nbsp;&nbsp;
        <%=link_to "Inbox", inbox_path, :class => 'lih4' %>
          </li>

        <% if controller_name == "notes" && action_name == "all_notes" %>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %>
        <%=link_to "All Notes", all_notes_path, :class => 'lih3' %>
          </li>

        <hr class="menu"></hr>

        <% if controller_name == "sources" && action_name == "my_sources" %>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %>
        <%=link_to "My Sources", my_sources_path, :class => 'lih3' %>
          </li>

        <% if controller_name == "sources" && action_name == "inbox"%>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %>&nbsp;
        <%=link_to "Unattributed Sources", inbox_sources_path, :class => 'lih4' %>
          </li>

        <% if controller_name == "sources" && action_name == "all_sources" %>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %>
        <%=link_to "All Sources", all_sources_path, :class => 'lih3' %>
          </li>

      <hr class="menu"></hr>

        <% if controller_name == "users" %>
          <li class="active-heading">
        <% else %>
          <li>
        <% end %>
        <%=link_to "People", users_path, :class => 'lih3' %>
          </li>

        <hr class="menu"></hr>

      </ul>
 
      <% else %>
        <h4>Please log in.</h4>
      <% end %>
    </div>
  </div><!-- end left -->

  <div id="right">
    <div id="content">
      <p style="color: green"><%= notice %></p>
      <p style="color: red"><%= flash[:error] %></p>

      <%= yield %>
    </div><!-- end content -->
  </div><!-- end right -->
  </div><!-- end main -->
</div><!-- end page -->

</body>
</html>